baseURL = 'https://rolloworsley.pages.dev/'
languageCode = 'en-us'
title = 'Rolloworsley'
theme = 'PaperMod'
paginate = "10"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
	  
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = 'production'
  author = 'Osgood'
  images = ["<link or path of image for opengraph, twitter-cards>"]
  defaultTheme = 'auto' 
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false
